### ISSUE TITLE
Error occurred when building on Gatsby Cloud

### ISSUE THREAD

**Issue by viperfx** [kmcaloon/gatsby-groq#3]
Hi there, 

It me again. I happened to be trying out gatsby cloud to check out the sanity live preview and noticed that the build had an error related to this plugin.

```
"gatsby-plugin-groq" threw an error while running the resolvableExtensions lifecycle: ENOENT: no such file or directory, mkdir 'undefined/public/static/groq' 26 | fs.rmdirSync( GROQ_DIR, { recursive: true } ); 27 | } > 28 | fs.mkdirSync( GROQ_DIR ); | ^ 29 | 30 | // Cache fragments. 31 | const fragmentsDir = !! plugin.fragmentsDir ? path.join( ROOT, plugin.fragmentsDir ) : null;
```

Just thought I would let you know.

**Comment by kmcaloon** [comment]
Nice, keep these coming! It really helps. Just published a new release when you get a chance can you upgrade and check to see if that fixes it?

**Comment by viperfx** [comment]
Yep that works! Thanks.
